name: Build and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    name: Build with ${{ matrix.build_system }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_system: [fpm, meson]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gfortran \
            libomp-dev \
            libopenblas-dev \
            liblapack-dev \
            meson

      - name: Install fpm
        if: matrix.build_system == 'fpm'
        uses: fortran-lang/setup-fpm@v5
        with:
          fpm-version: 'v0.9.0'

      - name: Build and Test (Debug) with fpm
        if: matrix.build_system == 'fpm'
        run: |
          fpm build
          fpm test
          fpm run gpd_coulomb_schroed_nelements

      - name: Build and Test (Release) with fpm
        if: matrix.build_system == 'fpm'
        run: |
          fpm test --profile=release
          fpm run --profile=release gpd_coulomb_schroed_nelements

      - name: Configure and Build with meson
        if: matrix.build_system == 'meson'
        run: |
          meson setup builddir -Dwith_tests=True -Dwith_app=True
          meson compile -C builddir

      - name: Test with meson
        if: matrix.build_system == 'meson'
        run: meson test -C builddir

      - name: Run convergence app with meson
        if: matrix.build_system == 'meson'
        run: ./builddir/app/gpd_coulomb_schroed_nelements
