name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'

      - name: Prepare Doxygen prerequisites
        shell: bash -el {0}
        run: |
          cd apidocs
          # Get external tags for C++ standard library linking
          mkdir -p tags
          curl -L https://upload.cppreference.com/mwiki/images/f/f8/cppreference-doxygen-web.tag.xml -o tags/cppreference-doxygen-web.tag.xml
          # Get the Doxygen theme
          wget https://github.com/HaoZeke/doxyYoda/releases/download/0.0.2/doxyYoda_0.0.2.tar.gz
          tar xf doxyYoda_0.0.2.tar.gz

      - name: Generate Doxygen documentation
        shell: bash -el {0}
        run: doxygen apidocs/Doxygen-featom.cfg

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: html/
          if-no-files-found: error
  deploy:
    needs: build_docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'atomic-solvers/featom'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
